vlog -work work C:/Users/Aluno/Downloads/SDA-Prova-master/Upsampling/simulation/modelsim/Waveform.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.Upsampling_vlg_vec_tst
onerror {resume}
add wave {Upsampling_vlg_vec_tst/i1/clk}
add wave {Upsampling_vlg_vec_tst/i1/newLine}
add wave {Upsampling_vlg_vec_tst/i1/reset}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn[7]}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn[6]}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn[5]}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn[4]}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn[3]}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn[2]}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn[1]}
add wave {Upsampling_vlg_vec_tst/i1/sampleIn[0]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1[7]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1[6]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1[5]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1[4]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1[3]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1[2]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1[1]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut1[0]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2[7]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2[6]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2[5]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2[4]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2[3]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2[2]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2[1]}
add wave {Upsampling_vlg_vec_tst/i1/sampleOut2[0]}
add wave {Upsampling_vlg_vec_tst/i1/start}
add wave {Upsampling_vlg_vec_tst/i1/valido}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0[7]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0[6]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0[5]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0[4]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0[3]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0[2]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0[1]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN0[0]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1[7]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1[6]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1[5]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1[4]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1[3]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1[2]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1[1]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN1[0]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2[7]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2[6]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2[5]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2[4]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2[3]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2[2]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2[1]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN2[0]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3[7]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3[6]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3[5]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3[4]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3[3]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3[2]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3[1]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN3[0]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4[7]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4[6]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4[5]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4[4]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4[3]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4[2]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4[1]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN4[0]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5[7]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5[6]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5[5]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5[4]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5[3]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5[2]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5[1]}
add wave {Upsampling_vlg_vec_tst/i1/Interpolador1/amostraIN5[0]}
run -all
